// Sample book data for the catalog
export const books = [
  {
    id: "1",
    title: "The Midnight Library",
    author: "Matt Haig",
    year: 2020,
    isNew: true,
    description:
      "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "fantasy", "philosophical"],
    formats: ["print", "ebook", "audiobook"],
    available: true,
    isbn: "9780525559474",
    pages: 304,
    publisher: "Viking",
    language: "English",
  },
  {
    id: "2",
    title: "Atomic Habits",
    author: "James Clear",
    year: 2018,
    isNew: true,
    description:
      "No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear reveals practical strategies that will teach you how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["nonfiction", "self-help", "psychology"],
    formats: ["print", "ebook"],
    available: true,
    isbn: "9780735211292",
    pages: 320,
    publisher: "Avery",
    language: "English",
  },
  {
    id: "3",
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    year: 2020,
    isNew: true,
    description:
      "A life no one will remember. A story you will never forget. France, 1714: In a moment of desperation, a young woman makes a Faustian bargain to live forever—and is cursed to be forgotten by everyone she meets.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "fantasy", "historical"],
    formats: ["print", "ebook", "audiobook"],
    available: false,
    isbn: "9780765387561",
    pages: 448,
    publisher: "Tor Books",
    language: "English",
  },
  {
    id: "4",
    title: "Project Hail Mary",
    author: "Andy Weir",
    year: 2021,
    isNew: true,
    description:
      "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the Earth itself will perish. Except that right now, he doesn't know that. He can't even remember his own name, let alone the nature of his assignment or how to complete it.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "scifi", "adventure"],
    formats: ["print", "ebook"],
    available: true,
    isbn: "9780593135204",
    pages: 496,
    publisher: "Ballantine Books",
    language: "English",
  },
  {
    id: "5",
    title: "Educated",
    author: "Tara Westover",
    year: 2018,
    isNew: false,
    description:
      "An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["nonfiction", "memoir", "biography"],
    formats: ["print", "ebook", "audiobook"],
    available: true,
    isbn: "9780399590504",
    pages: 352,
    publisher: "Random House",
    language: "English",
  },
  {
    id: "6",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    year: 2018,
    isNew: false,
    description:
      "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "mystery", "coming-of-age"],
    formats: ["print", "ebook"],
    available: false,
    isbn: "9780735219090",
    pages: 384,
    publisher: "G.P. Putnam's Sons",
    language: "English",
  },
  {
    id: "7",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    year: 2019,
    isNew: false,
    description:
      "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London's most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "mystery", "thriller", "psychological"],
    formats: ["print", "ebook", "audiobook"],
    available: true,
    isbn: "9781250301697",
    pages: 336,
    publisher: "Celadon Books",
    language: "English",
  },
  {
    id: "8",
    title: "Becoming",
    author: "Michelle Obama",
    year: 2018,
    isNew: false,
    description:
      "In her memoir, a work of deep reflection and mesmerizing storytelling, Michelle Obama invites readers into her world, chronicling the experiences that have shaped her—from her childhood on the South Side of Chicago to her years as an executive balancing the demands of motherhood and work, to her time spent at the world's most famous address.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["nonfiction", "memoir", "biography", "autobiography"],
    formats: ["print", "ebook", "audiobook"],
    available: true,
    isbn: "9781524763138",
    pages: 448,
    publisher: "Crown",
    language: "English",
  },
  {
    id: "9",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    year: 1937,
    isNew: false,
    description:
      "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "fantasy", "classic", "adventure"],
    formats: ["print", "ebook", "audiobook"],
    available: true,
    isbn: "9780547928227",
    pages: 300,
    publisher: "Houghton Mifflin Harcourt",
    language: "English",
  },
  {
    id: "10",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: 1960,
    isNew: false,
    description:
      "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. 'To Kill A Mockingbird' became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "classic", "historical"],
    formats: ["print", "ebook"],
    available: false,
    isbn: "9780061120084",
    pages: 336,
    publisher: "Harper Perennial Modern Classics",
    language: "English",
  },
  {
    id: "11",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    year: 1925,
    isNew: false,
    description:
      "The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted 'gin was the national drink and sex the national obsession,' it is an exquisitely crafted tale of America in the 1920s.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "classic", "literary"],
    formats: ["print", "ebook", "audiobook"],
    available: true,
    isbn: "9780743273565",
    pages: 180,
    publisher: "Scribner",
    language: "English",
  },
  {
    id: "12",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    year: 1813,
    isNew: false,
    description:
      "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work 'her own darling child' and its vivacious heroine, Elizabeth Bennet, 'as delightful a creature as ever appeared in print.'",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "classic", "romance"],
    formats: ["print", "ebook", "audiobook"],
    available: true,
    isbn: "9780141439518",
    pages: 480,
    publisher: "Penguin Classics",
    language: "English",
  },
  {
    id: "13",
    title: "1984",
    author: "George Orwell",
    year: 1949,
    isNew: false,
    description:
      "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell's nightmarish vision of a totalitarian, bureaucratic world and one poor stiff's attempt to find individuality.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "classic", "dystopian", "scifi"],
    formats: ["print", "ebook"],
    available: true,
    isbn: "9780451524935",
    pages: 328,
    publisher: "Signet Classics",
    language: "English",
  },
  {
    id: "14",
    title: "The Alchemist",
    author: "Paulo Coelho",
    year: 1988,
    isNew: false,
    description:
      "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "philosophical", "spiritual"],
    formats: ["print", "ebook", "audiobook"],
    available: false,
    isbn: "9780062315007",
    pages: 208,
    publisher: "HarperOne",
    language: "English",
  },
  {
    id: "15",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    year: 1951,
    isNew: false,
    description:
      "The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caulfield. Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "classic", "coming-of-age"],
    formats: ["print"],
    available: true,
    isbn: "9780316769488",
    pages: 277,
    publisher: "Little, Brown and Company",
    language: "English",
  },
  {
    id: "16",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    year: 1997,
    isNew: false,
    description:
      "Harry Potter has no idea how famous he is. That's because he's being raised by his miserable aunt and uncle who are terrified Harry will learn that he's really a wizard, just as his parents were.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "fantasy", "young-adult"],
    formats: ["print", "ebook", "audiobook"],
    available: true,
    isbn: "9780590353427",
    pages: 309,
    publisher: "Scholastic",
    language: "English",
  },
  {
    id: "17",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    year: 1954,
    isNew: false,
    description:
      "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them. In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "fantasy", "classic", "adventure"],
    formats: ["print", "ebook"],
    available: false,
    isbn: "9780618640157",
    pages: 1178,
    publisher: "Mariner Books",
    language: "English",
  },
  {
    id: "18",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    year: 2003,
    isNew: false,
    description:
      "While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "mystery", "thriller"],
    formats: ["print", "ebook", "audiobook"],
    available: true,
    isbn: "9780307474278",
    pages: 597,
    publisher: "Anchor",
    language: "English",
  },
  {
    id: "19",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    year: 2008,
    isNew: false,
    description:
      "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "dystopian", "young-adult", "scifi"],
    formats: ["print", "ebook"],
    available: true,
    isbn: "9780439023528",
    pages: 374,
    publisher: "Scholastic Press",
    language: "English",
  },
  {
    id: "20",
    title: "The Shining",
    author: "Stephen King",
    year: 1977,
    isNew: false,
    description:
      "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "horror", "thriller"],
    formats: ["print", "ebook", "audiobook"],
    available: false,
    isbn: "9780307743657",
    pages: 688,
    publisher: "Anchor",
    language: "English",
  },
  {
    id: "21",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    year: 2014,
    isNew: false,
    description:
      "From a renowned historian comes a groundbreaking narrative of humanity's creation and evolution—a #1 international bestseller—that explores the ways in which biology and history have defined us and enhanced our understanding of what it means to be 'human'.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["nonfiction", "history", "science", "anthropology"],
    formats: ["print", "ebook", "audiobook"],
    available: true,
    isbn: "9780062316097",
    pages: 464,
    publisher: "Harper",
    language: "English",
  },
  {
    id: "22",
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    year: 2005,
    isNew: false,
    description:
      "Harriet Vanger, a scion of one of Sweden's wealthiest families disappeared over forty years ago. All these years later, her aged uncle continues to seek the truth. He hires Mikael Blomkvist, a crusading journalist recently trapped by a libel conviction, to investigate.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "mystery", "thriller", "crime"],
    formats: ["print", "ebook"],
    available: true,
    isbn: "9780307454546",
    pages: 672,
    publisher: "Vintage Crime/Black Lizard",
    language: "English",
  },
  {
    id: "23",
    title: "The Road",
    author: "Cormac McCarthy",
    year: 2006,
    isNew: false,
    description:
      "A father and his son walk alone through burned America. Nothing moves in the ravaged landscape save the ash on the wind. It is cold enough to crack stones, and when the snow falls it is gray. The sky is dark. Their destination is the coast, although they don't know what, if anything, awaits them there.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "dystopian", "post-apocalyptic"],
    formats: ["print", "ebook", "audiobook"],
    available: false,
    isbn: "9780307387899",
    pages: 287,
    publisher: "Vintage",
    language: "English",
  },
  {
    id: "24",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    year: 2003,
    isNew: false,
    description:
      "The unforgettable, heartbreaking story of the unlikely friendship between a wealthy boy and the son of his father's servant, The Kite Runner is a beautifully crafted novel set in a country that is in the process of being destroyed.",
    coverImage: "https://placehold.co/600x400",
    subjects: ["fiction", "historical", "cultural"],
    formats: ["print", "ebook"],
    available: true,
    isbn: "9781594631931",
    pages: 371,
    publisher: "Riverhead Books",
    language: "English",
  },
];
