// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/catalog": {
    params: {};
  };
  "/book/:id": {
    params: {
      "id": string;
    };
  };
  "/news": {
    params: {};
  };
  "/news/:id": {
    params: {
      "id": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/users/new": {
    params: {};
  };
  "/admin/users/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/news": {
    params: {};
  };
  "/admin/news/new": {
    params: {};
  };
  "/admin/news/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/books": {
    params: {};
  };
  "/admin/books/new": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/catalog" | "/book/:id" | "/news" | "/news/:id" | "/admin" | "/admin/users" | "/admin/users/new" | "/admin/users/:id/edit" | "/admin/news" | "/admin/news/new" | "/admin/news/:id/edit" | "/admin/books" | "/admin/books/new" | "/login" | "/sign-up";
  };
  "./routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/catalog" | "/book/:id" | "/news" | "/news/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/catalog.tsx": {
    id: "routes/catalog";
    page: "/catalog";
  };
  "./routes/book-detail.tsx": {
    id: "routes/book-detail";
    page: "/book/:id";
  };
  "./routes/news.tsx": {
    id: "routes/news";
    page: "/news";
  };
  "./routes/news-detail.tsx": {
    id: "routes/news-detail";
    page: "/news/:id";
  };
  "./routes/admin/layout.tsx": {
    id: "routes/admin/layout";
    page: "/admin" | "/admin/users" | "/admin/users/new" | "/admin/users/:id/edit" | "/admin/news" | "/admin/news/new" | "/admin/news/:id/edit" | "/admin/books" | "/admin/books/new";
  };
  "routes/admin/index.tsx": {
    id: "routes/admin/index";
    page: "/admin";
  };
  "./routes/admin/users/index.tsx": {
    id: "routes/admin/users/index";
    page: "/admin/users";
  };
  "./routes/admin/users/new.tsx": {
    id: "routes/admin/users/new";
    page: "/admin/users/new";
  };
  "./routes/admin/users/edit.tsx": {
    id: "routes/admin/users/edit";
    page: "/admin/users/:id/edit";
  };
  "./routes/admin/news/index.tsx": {
    id: "routes/admin/news/index";
    page: "/admin/news";
  };
  "./routes/admin/news/new.tsx": {
    id: "routes/admin/news/new";
    page: "/admin/news/new";
  };
  "./routes/admin/news/edit.tsx": {
    id: "routes/admin/news/edit";
    page: "/admin/news/:id/edit";
  };
  "./routes/admin/books/index.tsx": {
    id: "routes/admin/books/index";
    page: "/admin/books";
  };
  "./routes/admin/books/new.tsx": {
    id: "routes/admin/books/new";
    page: "/admin/books/new";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/sign-up.tsx": {
    id: "routes/sign-up";
    page: "/sign-up";
  };
};